# Generated by Django 4.1.7 on 2023-03-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_place', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.plane')),
            ],
        ),
    ]
