# Generated by Django 4.1.7 on 2023-04-10 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight_price_business_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price_business_class',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price_economy_class',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price_first_class',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
