# Generated by Django 4.1.7 on 2023-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('seats_first_class', models.IntegerField()),
                ('seats_business', models.IntegerField()),
                ('seats_economy', models.IntegerField()),
                ('luggage_capacity', models.FloatField()),
            ],
        ),
    ]
